behaviors:
  KinematicMoveToGoal:
    trainer_type: ppo
    threaded: true
    hyperparameters:
      batch_size: 1000
      buffer_size: 10000
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000